dist: xenial
language: php
compiler:
    - gcc
services:
    - docker
stages:
    - master_test
    - test
jobs:
    allow_failures:
        - stage: test
          php: nightly
          env: LIBRDKAFKA_VERSION=0.11.x
        - stage: test
          php: nightly
          env: LIBRDKAFKA_VERSION=v1.0.1
        - stage: test
          php: nightly
          env: LIBRDKAFKA_VERSION=v1.1.0
        - stage: test
          php: nightly
          env: LIBRDKAFKA_VERSION=v1.2.2
        - stage: test
          php: nightly
          env: LIBRDKAFKA_VERSION=master
    include:
        - env: LIBRDKAFKA_VERSION=v1.2.2 MEMORY_CHECK=1 PHP_VERSION=7.4.0
          stage: master_test
          name: Master Test
          addons:
              apt:
                  packages:
                      - valgrind
                      - libonig-dev
                      - libzip-dev

        - php: 5.6
          stage: test
          env: LIBRDKAFKA_VERSION=0.11.x
        - php: 7.0
          env: LIBRDKAFKA_VERSION=0.11.x
        - php: 7.1
          env: LIBRDKAFKA_VERSION=0.11.x
        - php: 7.2
          env: LIBRDKAFKA_VERSION=0.11.x
        - php: 7.3
          env: LIBRDKAFKA_VERSION=0.11.x
        - php: 7.4
          env: LIBRDKAFKA_VERSION=0.11.x

        - php: 5.6
          env: LIBRDKAFKA_VERSION=v1.0.1
        - php: 7.0
          env: LIBRDKAFKA_VERSION=v1.0.1
        - php: 7.1
          env: LIBRDKAFKA_VERSION=v1.0.1
        - php: 7.2
          env: LIBRDKAFKA_VERSION=v1.0.1
        - php: 7.3
          env: LIBRDKAFKA_VERSION=v1.0.1
        - php: 7.4
          env: LIBRDKAFKA_VERSION=v1.0.1

        - php: 5.6
          env: LIBRDKAFKA_VERSION=v1.1.0
        - php: 7.0
          env: LIBRDKAFKA_VERSION=v1.1.0
        - php: 7.1
          env: LIBRDKAFKA_VERSION=v1.1.0
        - php: 7.2
          env: LIBRDKAFKA_VERSION=v1.1.0
        - php: 7.3
          env: LIBRDKAFKA_VERSION=v1.1.0
        - php: 7.4
          env: LIBRDKAFKA_VERSION=v1.1.0

        - php: 5.6
          env: LIBRDKAFKA_VERSION=v1.2.2
        - php: 7.0
          env: LIBRDKAFKA_VERSION=v1.2.2
        - php: 7.1
          env: LIBRDKAFKA_VERSION=v1.2.2
        - php: 7.2
          env: LIBRDKAFKA_VERSION=v1.2.2
        - php: 7.3
          env: LIBRDKAFKA_VERSION=v1.2.2
        - php: 7.4
          env: LIBRDKAFKA_VERSION=v1.2.2

        - php: 5.6
          env: LIBRDKAFKA_VERSION=master
        - php: 7.0
          env: LIBRDKAFKA_VERSION=master
        - php: 7.1
          env: LIBRDKAFKA_VERSION=master
        - php: 7.2
          env: LIBRDKAFKA_VERSION=master
        - php: 7.3
          env: LIBRDKAFKA_VERSION=master
        - php: 7.4
          env: LIBRDKAFKA_VERSION=master

before_install:
    - |
      set -e;
      if [ -n "$MEMORY_CHECK" ]; then
          export PHP_BUILD_CONFIGURE_OPTS="--enable-debug";
          git clone git://github.com/php-build/php-build.git $HOME/.phpenv/plugins/php-build;
          travis_wait phpenv install $PHP_VERSION;
          phpenv rehash;
          phpenv global $PHP_VERSION;
      fi
    - |
      # Start Kafka and install an up-to-date librdkafka
      docker network create kafka_network
      docker pull wurstmeister/zookeeper:3.4.6
      docker run -d --network kafka_network --name zookeeper wurstmeister/zookeeper:3.4.6
      docker pull wurstmeister/kafka:2.12-2.3.1
      docker run -d -p 9092:9092 --network kafka_network -e "KAFKA_AUTO_CREATE_TOPICS_ENABLE=true" -e "KAFKA_CREATE_TOPICS=test-topic:1:1:compact" -e "KAFKA_ADVERTISED_HOST_NAME=kafka" -e "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181" -e "KAFKA_ADVERTISED_PORT=9092" --name kafka wurstmeister/kafka:2.12-2.3.1
      export KAFKA_BROKER=kafka:9092
      sudo sh -c 'echo "\n127.0.0.1  kafka\n" >> /etc/hosts'

      mkdir /tmp/librdkafka
      cd /tmp/librdkafka
      git clone --depth 1 --branch "${LIBRDKAFKA_VERSION:-v1.2.2}" "${LIBRDKAFKA_REPOSITORY_URL:-https://github.com/edenhill/librdkafka.git}" .
      ./configure && make && sudo make install
      cd -
    - set -e
install:
    - sudo ldconfig
    - echo "extension = $(pwd)/modules/rdkafka.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - phpenv config-rm xdebug.ini || true
    - phpize
    - CFLAGS='-Werror=implicit-function-declaration' ./configure && make
before_script:
    - |
      export TEST_KAFKA_BROKERS=kafka:9092
      export TEST_KAFKA_BROKER_VERSION=2.3
      export LIBRDKAFKA_REPOSITORY_URL=https://github.com/edenhill/librdkafka.git
script:
    - export PATH=$TRAVIS_BUILD_DIR/.travis:$PATH
    ### Issues with environmental variables causes this copy to be required
    - cp tests/test_env.php.sample tests/test_env.php
    - PHP=$(which php)
    - |
      showmem=
      checkmem=
      if [ -n "$MEMORY_CHECK" ] && [ grep -q 'cfgfiles.*mem' run-tests.php ]; then
          echo "Will enable the --show-mem flag"
          showmem=--show-mem
      fi
      if [ -n "$MEMORY_CHECK" ]; then
          checkmem=-m
      fi
    - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE="$PHP" "$PHP" run-tests.php $checmmem -q --show-diff $showmem
